### ISSUE TITLE
Add Qvault dev profiles

### ISSUE THREAD

**Issue by lane-c-wagner** [qeeqbox/social-analyzer#37]
I can open a PR to add [Qvault](https://qvault.io) developer profiles if you think it would be a good fit. Let me know :)

**Comment by giga-a** [comment]
Hey lane-c-Wagner, thanks for reaching out!  It might not be possible due to some Detection Verification tests that run by My Dedicated Testing System (Macaw) **before** pushing that detection to GitHub. One of them verifies detections based on website metrics & metadata, which may cause the test to fail. I'm closing this request for now. But, will keep you in mind!
